### ISSUE TITLE
When train CAR

### ISSUE THREAD

**Issue by yujiaolong1120** [MC-E/COLA-Net-Collaborative-Attention-Network-for-Image-Restoration#2]
FileNotFoundError: [Error 2] No such file or directory: 'DIV2K/DIV2K_LQ/10'

**Comment by MC-E** [comment]
You need to prepare the training pairs. The LQ images need to be placed in DIV2K/DIV2K_LQ/x, where 'x' refers to the quality factor (10, 20, 30, and 40).
